In [1]:
import pickle

In [2]:
with open("C:/Users/12533/Desktop/Fall 2022/COMSE 6901/Fall 2022/MOMS-PI dataset/mixture/16s/16s_tables.pkl", "rb") as f:
    tables = pickle.load(f)

In [3]:
import biom

In [4]:
tables

{'MCVD': 1246 x 162 <class 'biom.table.Table'> with 7185 nonzero entries (3% dense),
 'BC1D': 905 x 47 <class 'biom.table.Table'> with 2038 nonzero entries (4% dense),
 'BRCD': 2374 x 967 <class 'biom.table.Table'> with 31133 nonzero entries (1% dense),
 'BS1D': 2270 x 734 <class 'biom.table.Table'> with 30595 nonzero entries (1% dense),
 'MV1D': 3434 x 2055 <class 'biom.table.Table'> with 121282 nonzero entries (1% dense),
 'MCHD': 956 x 152 <class 'biom.table.Table'> with 3079 nonzero entries (2% dense),
 'BCKD': 2719 x 964 <class 'biom.table.Table'> with 40975 nonzero entries (1% dense),
 'BSTD': 538 x 37 <class 'biom.table.Table'> with 1602 nonzero entries (8% dense),
 'MCKD': 3748 x 2327 <class 'biom.table.Table'> with 286063 nonzero entries (3% dense),
 'MRCD': 6251 x 1725 <class 'biom.table.Table'> with 399902 nonzero entries (3% dense)}

In [5]:
tables['MCKD'].to_dataframe()

,EP004835_K10,EP004835_K20,EP004835_K30,EP004835_K40,EP004835_K50,EP004835_K70,EP005972_K10,EP005972_K20,EP005972_K50,EP007214_K10,...,EP996091_K20,EP996091_K30,EP996091_K40,EP996091_K50,EP996091_K60,EP997385_K10,EP997385_K130,EP997385_K20,EP997385_K40,EP997385_K70
1000547,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1005533,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1007399,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1007430,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100791,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995155,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
995822,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
995893,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99634,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
999477,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
# Top 10% densest clades
top10_clades = (tables['MCKD'].to_dataframe() > 0).sum(axis=1).sort_values()[-375:]
top10_clades

4448211     185
92316       186
303643      188
359538      188
2217384     190
           ...
518743     1933
516648     1937
272150     1955
535353     1971
529233     2273
Length: 375, dtype: int64

In [15]:
# Normalization: make every sample sum to 1

mckd_normed = tables['MCKD'].norm(axis='sample', inplace=False)
mckd_normed.to_dataframe().sum(axis=0) # Should be 1

EP004835_K10     1.0
EP004835_K20     1.0
EP004835_K30     1.0
EP004835_K40     1.0
EP004835_K50     1.0
                ...
EP997385_K10     1.0
EP997385_K130    1.0
EP997385_K20     1.0
EP997385_K40     1.0
EP997385_K70     1.0
Length: 2327, dtype: float64

In [16]:
mckd_normed_top10 = mckd_normed.filter(top10_clades.index, axis='observation', inplace=False) # Filter to top 10% densest clades
mckd_normed_top10

375 x 2327 <class 'biom.table.Table'> with 231773 nonzero entries (26% dense)

In [17]:
mckd_normed_top10.to_dataframe().columns

Index(['EP004835_K10', 'EP004835_K20', 'EP004835_K30', 'EP004835_K40',
       'EP004835_K50', 'EP004835_K70', 'EP005972_K10', 'EP005972_K20',
       'EP005972_K50', 'EP007214_K10',
       ...
       'EP996091_K20', 'EP996091_K30', 'EP996091_K40', 'EP996091_K50',
       'EP996091_K60', 'EP997385_K10', 'EP997385_K130', 'EP997385_K20',
       'EP997385_K40', 'EP997385_K70'],
      dtype='object', length=2327)

In [22]:
import pandas as pd

colnames_split = [x.split("_") for x in mckd_normed_top10.to_dataframe().columns]
colnames_split2 = [(patient, int(visit[1:-1])) for (patient, visit) in colnames_split]
mckd_normed_top10_reindexed = mckd_normed_top10.copy().to_dataframe()
mckd_normed_top10_reindexed.columns = pd.MultiIndex.from_tuples(colnames_split2) # Make a multiindex with patient and visit
# Sort by patient and visit
mckd_normed_top10_reindexed = mckd_normed_top10_reindexed.sort_index(axis=1, level=1) # Sort by visit
mckd_normed_top10_reindexed = mckd_normed_top10_reindexed.sort_index(axis=1, level=0) # Sort by patient
mckd_normed_top10_reindexed

         EP004835                                              EP005972  \
               1         2         3    4         5         7        1
1011398  0.000000  0.029058  0.000000  0.0  0.002532  0.000000      0.0
1017181  0.000000  0.000000  0.000000  0.0  0.000000  0.000000      0.0
1021043  0.000044  0.000000  0.000008  0.0  0.000000  0.000000      0.0
1026498  0.005259  0.002270  0.000000  0.0  0.000000  0.000000      0.0
1036749  0.000000  0.000000  0.000000  0.0  0.000044  0.000040      0.0
...           ...       ...       ...  ...       ...       ...      ...
925707   0.000000  0.000000  0.000000  0.0  0.000011  0.000008      0.0
92629    0.000000  0.000000  0.000000  0.0  0.000077  0.000000      0.0
92721    0.000000  0.000000  0.000000  0.0  0.000000  0.000000      0.0
92874    0.000000  0.000000  0.000000  0.0  0.000771  0.000113      0.0
93000    0.000000  0.000000  0.000000  0.0  0.000000  0.000000      0.0

                            EP007214  ... EP996091                           \
               2         5        1   ...       3         4    5         6
1011398  0.000000  0.000000      0.0  ...      0.0  0.000000  0.0  0.000000
1017181  0.000000  0.000000      0.0  ...      0.0  0.000000  0.0  0.000021
1021043  0.000000  0.000000      0.0  ...      0.0  0.000000  0.0  0.000021
1026498  0.000000  0.001119      0.0  ...      0.0  0.000000  0.0  0.000000
1036749  0.000000  0.000000      0.0  ...      0.0  0.000000  0.0  0.000000
...           ...       ...      ...  ...      ...       ...  ...       ...
925707   0.000000  0.000000      0.0  ...      0.0  0.000150  0.0  0.000000
92629    0.000000  0.000000      0.0  ...      0.0  0.000000  0.0  0.000000
92721    0.000000  0.000000      0.0  ...      0.0  0.000000  0.0  0.000000
92874    0.020915  0.006280      0.0  ...      0.0  0.005715  0.0  0.002187
93000    0.000000  0.000000      0.0  ...      0.0  0.000000  0.0  0.000000

                  EP997385
               11       1         2         4    7         13
1011398  0.000000      0.0  0.000000  0.000000  0.0  0.000000
1017181  0.000068      0.0  0.000000  0.000000  0.0  0.000000
1021043  0.000000      0.0  0.000000  0.000000  0.0  0.000000
1026498  0.000000      0.0  0.000000  0.000000  0.0  0.001605
1036749  0.000068      0.0  0.000000  0.000000  0.0  0.000082
...           ...      ...       ...       ...  ...       ...
925707   0.000000      0.0  0.000000  0.000000  0.0  0.000206
92629    0.000000      0.0  0.000000  0.000000  0.0  0.000000
92721    0.000000      0.0  0.000000  0.000000  0.0  0.000000
92874    0.000000      0.0  0.002283  0.005305  0.0  0.000267
93000    0.000000      0.0  0.000000  0.000000  0.0  0.000000

[375 rows x 2327 columns]

In [23]:
mckd_diffs = mckd_normed_top10_reindexed.groupby(level=0, axis=1).diff() # Group by patient, then take difference between visits
mckd_diffs

        EP004835                                                   EP005972  \
              1         2         3         4         5         7        1
1011398      NaN  0.029058 -0.029058  0.000000  0.002532 -0.002532      NaN
1017181      NaN  0.000000  0.000000  0.000000  0.000000  0.000000      NaN
1021043      NaN -0.000044  0.000008 -0.000008  0.000000  0.000000      NaN
1026498      NaN -0.002989 -0.002270  0.000000  0.000000  0.000000      NaN
1036749      NaN  0.000000  0.000000  0.000000  0.000044 -0.000004      NaN
...          ...       ...       ...       ...       ...       ...      ...
925707       NaN  0.000000  0.000000  0.000000  0.000011 -0.000003      NaN
92629        NaN  0.000000  0.000000  0.000000  0.000077 -0.000077      NaN
92721        NaN  0.000000  0.000000  0.000000  0.000000  0.000000      NaN
92874        NaN  0.000000  0.000000  0.000000  0.000771 -0.000657      NaN
93000        NaN  0.000000  0.000000  0.000000  0.000000  0.000000      NaN

                            EP007214  ... EP996091                      \
               2         5        1   ...       3         4         5
1011398  0.000000  0.000000      NaN  ...      0.0  0.000000  0.000000
1017181  0.000000  0.000000      NaN  ...      0.0  0.000000  0.000000
1021043  0.000000  0.000000      NaN  ...      0.0  0.000000  0.000000
1026498  0.000000  0.001119      NaN  ...      0.0  0.000000  0.000000
1036749  0.000000  0.000000      NaN  ...      0.0  0.000000  0.000000
...           ...       ...      ...  ...      ...       ...       ...
925707   0.000000  0.000000      NaN  ...      0.0  0.000150 -0.000150
92629    0.000000  0.000000      NaN  ...      0.0  0.000000  0.000000
92721    0.000000  0.000000      NaN  ...      0.0  0.000000  0.000000
92874    0.020915 -0.014635      NaN  ...      0.0  0.005715 -0.005715
93000    0.000000  0.000000      NaN  ...      0.0  0.000000  0.000000

                            EP997385
               6         11       1         2         4         7         13
1011398  0.000000  0.000000      NaN  0.000000  0.000000  0.000000  0.000000
1017181  0.000021  0.000047      NaN  0.000000  0.000000  0.000000  0.000000
1021043  0.000021 -0.000021      NaN  0.000000  0.000000  0.000000  0.000000
1026498  0.000000  0.000000      NaN  0.000000  0.000000  0.000000  0.001605
1036749  0.000000  0.000068      NaN  0.000000  0.000000  0.000000  0.000082
...           ...       ...      ...       ...       ...       ...       ...
925707   0.000000  0.000000      NaN  0.000000  0.000000  0.000000  0.000206
92629    0.000000  0.000000      NaN  0.000000  0.000000  0.000000  0.000000
92721    0.000000  0.000000      NaN  0.000000  0.000000  0.000000  0.000000
92874    0.002187 -0.002187      NaN  0.002283  0.003022 -0.005305  0.000267
93000    0.000000  0.000000      NaN  0.000000  0.000000  0.000000  0.000000

[375 rows x 2327 columns]

In [26]:
'''for patientID, visitTimes in mckd_diffs.columns.tolist():
    print(patientID)
    print(visitTimes)'''
mckd_diffs['EP004835'][1]

1011398   NaN
1017181   NaN
1021043   NaN
1026498   NaN
1036749   NaN
           ..
925707    NaN
92629     NaN
92721     NaN
92874     NaN
93000     NaN
Name: 1, Length: 375, dtype: Sparse[float64, 0.0]

In [41]:
'''for i in mckd_diffs['EP004835'][1].index:
    print(i)'''
keep = pd.DataFrame(mckd_diffs['EP004835'][1])
# keep.loc['93000']
# mckd_diffs.dropna(axis=1, how='all')
mckd_diffs.loc['1105876']

EP004835  1          NaN
          2     0.000000
          3     0.000000
          4     0.000000
          5     0.000000
                  ...
EP997385  1          NaN
          2    -0.006191
          4    -0.002283
          7     0.000000
          13    0.000000
Name: 1105876, Length: 2327, dtype: Sparse[float64, 0.0]